Config scantimeout (#1)
nickjturner/homebridge-mi-temperature-and-humidity-sensor pull request #5
Opened 2023-08-26 20:43 UTC by dkatargin

Add scanTimeout config parameter which use seconds for device scan timeout. This should reduce battery usage.

2023-08-28 20:43 UTC, nickjturner requested changes
Looks good, can you also add to [config.schema.json](https://github.com/nickjturner/homebridge-mi-temperature-and-humidity-sensor/blob/247a36766982137bf391745c4c0147e1bc38f74e/config.schema.json) and the [README.md](https://github.com/nickjturner/homebridge-mi-temperature-and-humidity-sensor/blob/main/README.md)

2023-08-29 13:48 UTC, dkatargin commented
Thanks for reviewing! I added the requested changes to this commit: 6890d36c7382aedf4180508e60e2d184ed9ffd2c

2023-08-29 15:13 UTC, nickjturner commented on README.md
> +          "scanTimeout": 3600,
```suggestion
          "scanTimeout": 3600
```

2023-08-29 15:14 UTC, nickjturner approved these changes
LGTM

2023-08-29 15:14 UTC, merged